version: "3.8"

services:
  redis:
    image: "redis:7-alpine"
    container_name: redis
    ports:
      - "6379:6379"

  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis